### PR TITLE
Fix duplicated logs with multiple reporters

### PR DESCRIPTION
**Pull request by JTMCaplin**
Fixes duplicated logs from https://github.com/dmitryshindin/karma-jasmine-order-reporter/issues/4

### CODE REVIEW

**Comment by JTMCaplin** [comment]
This actually breaks it completely

**Comment by JTMCaplin** [comment]
Sorry for opening and closing several times, went through a few different iterations.

Okay, have adjusted this to work correctly now. Issue can be reproduced by using the dots reporter along with jasmine-order. In karma config have reporters: ["dots", "jasmine-order"]. 
This causes an issue, since as it's a child class of the base reporter, it outputs console statements from the browser, and there's also another reporter, in this case dots, which also outputs console statements from the browser, you end up with two lots of console statements. 

Originally had it disabled when it's not the last order, as angular had done, but it doesn't actually matter what order the list is. Unfortunately removing normal commonMsg logging removes ability for browser.log to work, so switched to using the base write function instead. 

So instead I've added a config option which can be enabled when using the reporter with other reporters that cause this issue, and can be set to false if the other reporter doesn't log, allowing best of both worlds.

**Comment by dil-btarkovacs** [comment]
any willing to merge this?

**Review by dmitryshindin — APPROVED** [review]
LGTM

**Pull request merged**
